### ISSUE TITLE
Adding a new aspect overwrites a previously added aspect

### ISSUE THREAD

**Issue by kondziu** [Sk1mble/fate-core-official#55] opened 2023-11-18 19:26 UTC
**Problem**

When I create aspects through the aspect editor, the new always aspect overwrites the previous aspect I create.

**Reproduction**

I'm creating aspects through "Setup Aspects" in Game settings. 

![Screenshot from 2023-11-18 20-18-38](https://github.com/Sk1mble/fate-core-official/assets/50334/071f63ff-64bb-4a0b-a3c2-df886c437efd)

I create a new aspect:

![Screenshot from 2023-11-18 20-19-08](https://github.com/Sk1mble/fate-core-official/assets/50334/82b3d685-6ae1-4fa1-bdc5-60483796541f)

The aspect gets created, I created another aspect.

![Screenshot from 2023-11-18 20-19-32](https://github.com/Sk1mble/fate-core-official/assets/50334/7d8b4962-e5c4-4230-86d2-5982ff36b5c6)

![Screenshot from 2023-11-18 20-19-53](https://github.com/Sk1mble/fate-core-official/assets/50334/183bbe8d-40d6-408f-a1d1-1260eb0981c5)

When I save the aspect, the new aspect is created, but the old aspect disappears:

![Screenshot from 2023-11-18 20-20-17](https://github.com/Sk1mble/fate-core-official/assets/50334/a49ba221-06d2-4ed9-b3a2-911dfcda699f)

**Additional notes**

I think this has something to do with the fact that aspects are all defined under the key `undefined`, which I see when I  export the aspects:

![Screenshot from 2023-11-18 20-23-29](https://github.com/Sk1mble/fate-core-official/assets/50334/7a5fb846-830c-42eb-9f18-d4c3d0fa343d)

When I import aspects from my own definition (with unique keys), the aspects do not get overwritten:

![Screenshot from 2023-11-18 20-30-08](https://github.com/Sk1mble/fate-core-official/assets/50334/98295712-f8e6-4c0b-8ca9-598d7be64cb7)

![Screenshot from 2023-11-18 20-30-25](https://github.com/Sk1mble/fate-core-official/assets/50334/cf1e7497-1a7e-4503-917f-3b94fc42abe8)

**Version information**

Fate Core Official 4.5.0.5
Foundry Virtual tabletop 315Version 11 Stable

**Comment by Sk1mble** [comment] 2023-11-18 20:35
Thank you for the comprehensive report, I was immediately able to replicate and identify the bug and pushed a fix as v 4.5.06.

It was caused by my work to switch from using names as object keys to using base 64 encoded versions of the name as the object key. Regrettably I referred to the wrong value on setting the new name when I was refactoring. If you have any aspects in an improper state with undefined keys they will get migrated on start up by the GM, so it would have worked if you'd refreshed between adding each aspect... although obviously that was not working as intedned!

This refactor proved to be very complex and I probably broke more things than I fixed in the short term, but in the long term it makes the system's name handling much more robust and should give rise to less issues overall. 

I have also been able to delete the code that replaced all periods in names with a symbol almost identical to a period, which was a hacky fix I've disliked for a long time!

**Closed by Sk1mble** 2023-11-18 20:35 UTC
